import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "app/lib/motion/**/*.test.ts",
      "app/lib/city/**/*.test.ts",
      "app/components/journey-transition/**/*.test.ts",
      "app/components/journey/**/*.test.ts",
      "app/components/globe-to-city/**/*.test.ts",
      "app/components/video/living-navigation/**/*.test.ts",
      "app/live/hooks/**/*.test.ts",
      "app/notifications/**/*.test.ts",
      "lib/rewards/**/*.test.ts",
      "lib/referral/**/*.test.ts",
      "lib/recommendations/**/*.test.ts",
      "lib/live/**/*.test.ts",
      "lib/env/**/*.test.ts",
      "lib/ios/**/*.test.ts",
      "lib/site/**/*.test.ts",
      "lib/geo/**/*.test.ts",
      "lib/world/**/*.test.ts",
      "lib/wallet/**/*.test.ts",
      "lib/revenue/**/*.test.ts",
      "lib/ueos/**/*.test.ts",
      "lib/activity-tiers/**/*.test.ts",
      "lib/accountDeletion/**/*.test.ts",
      "lib/media/**/*.test.ts",
      "lib/supabase/**/*.test.ts",
      "app/actions/**/*.test.ts",
      "lib/store/**/*.test.ts",
      "lib/stories/**/*.test.ts",
      "lib/search/**/*.test.ts",
      "lib/ads/**/*.test.ts",
      "lib/learning/**/*.test.ts",
      "app/components/learning/**/*.test.ts",
      "lib/ai/**/*.test.ts",
      "lib/privateAi/**/*.test.ts",
      "lib/aiDataPlatform/**/*.test.ts",
      "lib/knowledgeAcquisition/**/*.test.ts",
      "lib/i18n/**/*.test.ts",
      "lib/translationStudio/**/*.test.ts",
      "lib/articles/**/*.test.ts",
      "lib/content/**/*.test.ts",
      "lib/games/**/*.test.ts",
      "platforms/core/**/*.test.ts",
      "app/watch/**/*.test.ts",
      "app/messages/**/*.test.ts",
      "app/lib/video/**/*.test.ts",
      "app/lib/social/**/*.test.ts",
      "app/lib/nav/**/*.test.ts",
      "app/lib/product/**/*.test.ts",
      "app/components/product/**/*.test.ts",
      "app/components/home/**/*.test.ts",
      "app/create/**/*.test.ts",
      "app/components/social/**/*.test.ts",
      "app/signup/**/*.test.ts",
      "app/components/landing/**/*.test.ts",
    ],
  },
});
