select
  (select count(*) from supabase_migrations.schema_migrations) as schema_migrations_count,
  (select version from supabase_migrations.schema_migrations order by version desc limit 1) as live_tip,
  (select count(*) from supabase_migrations.schema_migrations where version = '20260934') as has_20260934,
  (select count(*) from supabase_migrations.schema_migrations where version = '20260935') as has_20260935,
  (select count(*) from supabase_migrations.schema_migrations where version = '20260936') as has_20260936,
  (select name from supabase_migrations.schema_migrations where version = '20260935') as name_20260935,
  (select name from supabase_migrations.schema_migrations where version = '20260936') as name_20260936,
  (select count(*)::bigint from public.profiles) as profiles_count,
  (select count(*)::bigint from public.profile_places) as profile_places_count,
  (select count(*)::bigint from public.profile_education) as profile_education_count,
  (select count(*)::bigint from public.profile_work) as profile_work_count,
  (select count(*)::bigint from public.profile_tags) as profile_tags_count,
  (select count(*)::bigint from public.profile_milestones) as profile_milestones_count,
  (select count(*)::bigint from public.profile_links) as profile_links_count,
  (select count(*)::bigint from public.communication_phone_identities) as phone_hash_count,
  (select count(*)::bigint from public.communication_privacy_settings) as privacy_settings_count,
  (select count(*)::bigint from public.communication_contact_sync_state) as contact_sync_count,
  to_regclass('public.learning_teacher_profiles') is not null as has_learning_teacher_profiles;
