/**
 * UM Core P1 — package identity smoke test.
 *
 * Confirms the isolated contracts package loads.
 * Does not exercise registries, buses, flags, or any runtime engine.
 */

import { describe, expect, it } from "vitest";
import {
  UM_CORE_CAPABILITY_REGISTRY_PHASE,
  UM_CORE_COMPLIANCE_ENGINE_PHASE,
  UM_CORE_EVENT_ROUTING_PHASE,
  UM_CORE_EVENT_TYPE_REGISTRY_PHASE,
  UM_CORE_DEPENDENCY_REGISTRY_PHASE,
  UM_CORE_FEATURE_FLAG_REGISTRY_PHASE,
  UM_CORE_FOUNDATION_PHASE,
  UM_CORE_HEALTH_DECLARATION_CATALOG_PHASE,
  UM_CORE_MANIFEST_VALIDATION_PHASE,
  UM_CORE_NAMING_REGISTRY_PHASE,
  UM_CORE_AGGREGATE_REGISTRY_FACADE_PHASE,
  UM_CORE_VALIDATOR_COMPOSITION_PHASE,
  UM_CORE_FLAG_EVALUATOR_PHASE,
  UM_CORE_CAPABILITY_ASSERTER_PHASE,
  UM_CORE_EVENT_PUBLISHER_PHASE,
  UM_CORE_HEALTH_REPORTER_PHASE,
  UM_CORE_HEALTH_DIAGNOSTICS_JOIN_PHASE,
  UM_CORE_DEPENDENCY_VALIDATOR_PHASE,
  UM_CORE_FLEET_HEALTH_AGGREGATION_PHASE,
  UM_CORE_SDK_CLIENT_FACTORY_PHASE,
  UM_CORE_BOUNDED_HEALTH_HISTORY_PHASE,
  UM_CORE_PLATFORM_CAPABILITY_COMPATIBILITY_PHASE,
  UM_CORE_PACKAGE_ID,
  UM_CORE_PACKAGE_LABEL,
  UM_CORE_REGISTRY_FOUNDATION_PHASE,
  UM_MATURITY_DESCRIPTORS,
} from "./index";

describe("um.core foundation P1 package identity", () => {
  it("exposes durable package identity literals", () => {
    expect(UM_CORE_PACKAGE_ID).toBe("um.core");
    expect(UM_CORE_FOUNDATION_PHASE).toBe("P1");
    expect(UM_CORE_MANIFEST_VALIDATION_PHASE).toBe("P2");
    expect(UM_CORE_COMPLIANCE_ENGINE_PHASE).toBe("P3");
    expect(UM_CORE_REGISTRY_FOUNDATION_PHASE).toBe("P4");
    expect(UM_CORE_CAPABILITY_REGISTRY_PHASE).toBe("P5");
    expect(UM_CORE_EVENT_TYPE_REGISTRY_PHASE).toBe("P6");
    expect(UM_CORE_EVENT_ROUTING_PHASE).toBe("P7");
    expect(UM_CORE_FEATURE_FLAG_REGISTRY_PHASE).toBe("P8");
    expect(UM_CORE_DEPENDENCY_REGISTRY_PHASE).toBe("P9");
    expect(UM_CORE_HEALTH_DECLARATION_CATALOG_PHASE).toBe("P10");
    expect(UM_CORE_NAMING_REGISTRY_PHASE).toBe("P11");
    expect(UM_CORE_AGGREGATE_REGISTRY_FACADE_PHASE).toBe("P12");
    expect(UM_CORE_VALIDATOR_COMPOSITION_PHASE).toBe("P13");
    expect(UM_CORE_FLAG_EVALUATOR_PHASE).toBe("P14");
    expect(UM_CORE_CAPABILITY_ASSERTER_PHASE).toBe("P15");
    expect(UM_CORE_EVENT_PUBLISHER_PHASE).toBe("P16");
    expect(UM_CORE_HEALTH_REPORTER_PHASE).toBe("P17");
    expect(UM_CORE_HEALTH_DIAGNOSTICS_JOIN_PHASE).toBe("P18");
    expect(UM_CORE_DEPENDENCY_VALIDATOR_PHASE).toBe("P19");
    expect(UM_CORE_FLEET_HEALTH_AGGREGATION_PHASE).toBe("P20");
    expect(UM_CORE_SDK_CLIENT_FACTORY_PHASE).toBe("P21");
    expect(UM_CORE_BOUNDED_HEALTH_HISTORY_PHASE).toBe("P22");
    expect(UM_CORE_PLATFORM_CAPABILITY_COMPATIBILITY_PHASE).toBe("P24");
    expect(UM_CORE_PACKAGE_LABEL).toBe("UM Core Platform");
  });

  it("exposes maturity descriptors for levels 0–4", () => {
    expect(UM_MATURITY_DESCRIPTORS).toHaveLength(5);
    expect(UM_MATURITY_DESCRIPTORS.map((d) => d.level)).toEqual([0, 1, 2, 3, 4]);
  });
});
