/** Unique human-readable titles. Keys are stable slugs (IDs stay the same). */
export const UNIQUE_TITLES = {
  "umtuba-originals-01": "Golden Horizon",
  "umtuba-originals-02": "Desert Pulse",
  "umtuba-originals-03": "Night Drive",
  "umtuba-originals-04": "Amber Current",
  "umtuba-originals-05": "Velvet Signal",
  "umtuba-originals-06": "Copper Sky",
  "umtuba-originals-07": "Quiet Ember",
  "umtuba-originals-08": "Lunar Thread",
  "umtuba-beats-01": "City Grid",
  "umtuba-beats-02": "Midnight Kick",
  "umtuba-beats-03": "Steel Pocket",
  "umtuba-beats-04": "Neon March",
  "umtuba-beats-05": "Low Tide Beat",
  "umtuba-beats-06": "Brick Pulse",
  "umtuba-beats-07": "After Hours",
  "umtuba-beats-08": "Dust Groove",
  "umtuba-cinematic-01": "Iron Dawn",
  "umtuba-cinematic-02": "Shadow Rise",
  "umtuba-cinematic-03": "Glass Cathedral",
  "umtuba-cinematic-04": "Last Light",
  "umtuba-cinematic-05": "Frozen Banner",
  "umtuba-cinematic-06": "Deep Chamber",
  "umtuba-cinematic-07": "Distant Crown",
  "umtuba-cinematic-08": "Storm Gate",
  "umtuba-ambient-01": "Soft Harbor",
  "umtuba-ambient-02": "Fog Room",
  "umtuba-ambient-03": "Pale Drift",
  "umtuba-ambient-04": "Still Water",
  "umtuba-ambient-05": "Cloud Shelf",
  "umtuba-ambient-06": "Moss Hour",
  "umtuba-ambient-07": "Silver Haze",
  "umtuba-ambient-08": "Open Meadow",
  "umtuba-transitions-01": "Soft Lift",
  "umtuba-transitions-02": "Cross Fade",
  "umtuba-transitions-03": "Rise Cut",
  "umtuba-transitions-04": "Drop Veil",
  "umtuba-transitions-05": "Slide North",
  "umtuba-transitions-06": "Bright Pass",
  "umtuba-transitions-07": "Quiet Turn",
  "umtuba-whoosh-01": "Fast Sweep",
  "umtuba-whoosh-02": "Air Blade",
  "umtuba-whoosh-03": "Paper Rush",
  "umtuba-whoosh-04": "Wind Slice",
  "umtuba-whoosh-05": "Silk Pass",
  "umtuba-whoosh-06": "Tunnel Whoosh",
  "umtuba-whoosh-07": "Night Gust",
  "umtuba-hits-01": "Heavy Stamp",
  "umtuba-hits-02": "Soft Knock",
  "umtuba-hits-03": "Glass Hit",
  "umtuba-hits-04": "Drum Punch",
  "umtuba-hits-05": "Door Thud",
  "umtuba-hits-06": "Snap Impact",
  "umtuba-hits-07": "Metal Tap",
  "umtuba-ui-01": "Soft Click",
  "umtuba-ui-02": "Bright Tick",
  "umtuba-ui-03": "Confirm Tap",
  "umtuba-ui-04": "Light Pop",
  "umtuba-ui-05": "Menu Chip",
  "umtuba-ui-06": "Done Beep",
  "umtuba-funny-01": "Wobble Walk",
  "umtuba-funny-02": "Silly Bounce",
  "umtuba-funny-03": "Cartoon Slide",
  "umtuba-funny-04": "Quack Step",
  "umtuba-funny-05": "Bounce Zip",
  "umtuba-funny-06": "Goofy Spin",
  "umtuba-nature-01": "Rain Patio",
  "umtuba-nature-02": "Wind Leaves",
  "umtuba-nature-03": "Creek Bed",
  "umtuba-nature-04": "Night Crickets",
  "umtuba-nature-05": "Shore Foam",
  "umtuba-nature-06": "Forest Drip",
  "umtuba-technology-01": "Data Chirp",
  "umtuba-technology-02": "Circuit Ping",
  "umtuba-technology-03": "Boot Tone",
  "umtuba-technology-04": "Sync Pulse",
  "umtuba-technology-05": "Laser Tick",
  "umtuba-technology-06": "Modem Flick",
  "umtuba-sports-01": "Crowd Burst",
  "umtuba-sports-02": "Whistle Cut",
  "umtuba-sports-03": "Court Bounce",
  "umtuba-sports-04": "Goal Horn",
  "umtuba-sports-05": "Sprint Hit",
  "umtuba-sports-06": "Tape Snap",
  "umtuba-celebration-01": "Party Rise",
  "umtuba-celebration-02": "Confetti Fan",
  "umtuba-celebration-03": "Toast Spark",
  "umtuba-celebration-04": "Victory Bell",
  "umtuba-celebration-05": "Fireworks Lift",
  "umtuba-celebration-06": "Cheer Wave",
  "umtuba-calm-01": "Warm Tea",
  "umtuba-calm-02": "Slow Breath",
  "umtuba-calm-03": "Evening Lamp",
  "umtuba-calm-04": "Quiet Garden",
  "umtuba-calm-05": "Soft Piano Bed",
  "umtuba-calm-06": "Still Room",
  "umtuba-loops-01": "Pocket Loop",
  "umtuba-loops-02": "Warm Cycle",
  "umtuba-loops-03": "Night Loop",
  "umtuba-loops-04": "Soft Motor",
  "umtuba-loops-05": "Easy Repeat",
};

export function titleForSlug(slug) {
  const title = UNIQUE_TITLES[slug];
  if (!title) throw new Error(`Missing unique title for ${slug}`);
  return title;
}
