import { LEGAL_PLACEHOLDERS, type LegalSection } from "./constants";

const { entityName, registeredAddress, legalEmail, governingLaw } =
  LEGAL_PLACEHOLDERS;

export const PRIVACY_TITLE = "Privacy Policy";

export const PRIVACY_INTRO =
  "This Privacy Policy explains how UMTUBA collects, uses, shares, and protects personal information when you use the Service. It should be read together with our Terms of Service.";

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    id: "collect",
    title: "Information We Collect",
    paragraphs: [
      "We collect information you provide, information generated by your use of the Service, and information from service providers that help us operate the platform.",
      "Categories are described below. Exact fields may vary by feature and region.",
    ],
  },
  {
    id: "profile",
    title: "Profile Data",
    paragraphs: [
      "Account identifiers (such as email), username, display name, bio, avatar, and similar profile fields you choose to provide.",
      "Public profiles may be visible to other users and, where indexed, to search engines.",
    ],
  },
  {
    id: "media",
    title: "Uploaded Media",
    paragraphs: [
      "Videos, images, captions, and related metadata you upload. Media may be processed for playback, thumbnails, moderation, and storage.",
      "Storage paths and signed URLs are used for private or time-limited access where applicable.",
    ],
  },
  {
    id: "stories",
    title: "Stories",
    paragraphs: [
      "Story media, captions, view events, and expiry metadata. Stories may be visible only to allowed audiences (for example, followers).",
      "View records may be retained for a limited period consistent with product design and this Policy.",
    ],
  },
  {
    id: "live",
    title: "Live",
    paragraphs: [
      "Live room titles, visibility settings, approximate location labels (such as city/country), participation/presence signals, and related session metadata.",
      "Precise coordinates, when collected for a host feature, are handled under stricter access controls and are not treated as public profile data.",
    ],
  },
  {
    id: "messages",
    title: "Messages",
    paragraphs: [
      "Message content, attachments metadata (if enabled), conversation participants, read/delivery state, and related timestamps.",
      "Messages are private between participants subject to safety, legal, and operational exceptions described in this Policy.",
    ],
  },
  {
    id: "device",
    title: "Device Information",
    paragraphs: [
      "Device type, browser or app version, operating system, language, and similar technical attributes needed for compatibility and security.",
    ],
  },
  {
    id: "logs",
    title: "Logs",
    paragraphs: [
      "Server and application logs such as IP address, request paths, error diagnostics, and anti-abuse signals.",
      "Logs are used for reliability, security, and abuse prevention.",
    ],
  },
  {
    id: "analytics",
    title: "Analytics",
    paragraphs: [
      "Aggregated and product analytics that help us understand feature usage and improve the Service.",
      "Where we use third-party analytics, we configure them consistent with this Policy and applicable consent requirements.",
    ],
  },
  {
    id: "cookies",
    title: "Cookies",
    paragraphs: [
      "We use cookies and similar technologies for authentication sessions, preferences, security, and measurement.",
      "You can control some cookies through browser settings; disabling essential cookies may break sign-in or core features.",
    ],
  },
  {
    id: "ads",
    title: "Ads",
    paragraphs: [
      "If you use advertiser tools, we process business contact details, campaign settings, creatives, and review outcomes needed to operate ads accounts.",
      "Ad delivery and personalized advertising may be limited or disabled until we enable those features. Targeting must follow our safety rules.",
    ],
  },
  {
    id: "store",
    title: "Store",
    paragraphs: [
      "Seller applications, store profiles, product listings, wishlist/cart activity, and related commerce metadata.",
      "Payment processing, if introduced, will be described in updated terms and may involve third-party payment providers.",
    ],
  },
  {
    id: "rewards",
    title: "Rewards",
    paragraphs: [
      "UM Points balances, ledger events, referral attribution, and reward preferences associated with your account.",
      "Reward data is used to operate loyalty features and prevent abuse.",
    ],
  },
  {
    id: "minors",
    title: "Minor Protection",
    paragraphs: [
      "We take additional care with features that may reach teens or minors, including advertising and targeting restrictions.",
      "If we learn we have collected personal information from a child in a manner not permitted by law, we will delete or restrict it as required.",
    ],
  },
  {
    id: "sharing",
    title: "Sharing with Providers",
    paragraphs: [
      "We share data with infrastructure and service providers (hosting, storage, email delivery, analytics, moderation tooling) under contractual confidentiality and purpose limits.",
      "We may disclose information to comply with law, protect users, or respond to valid legal process.",
    ],
  },
  {
    id: "retention",
    title: "Retention",
    paragraphs: [
      "We retain personal data for as long as needed to provide the Service, comply with legal obligations, resolve disputes, and enforce agreements.",
      "Some data (for example, expired Stories media) is designed to be deleted or become inaccessible after a short period, subject to backup and legal holds.",
    ],
  },
  {
    id: "security",
    title: "Security",
    paragraphs: [
      "We use administrative, technical, and organizational measures designed to protect personal data, including access controls and encrypted transport where appropriate.",
      "No method of transmission or storage is completely secure; please use a strong password and protect your devices.",
    ],
  },
  {
    id: "rights",
    title: "User Rights",
    paragraphs: [
      `Depending on your location, you may have rights to access, correct, delete, or export personal data, or to object to or restrict certain processing. Contact ${legalEmail} to submit a request.`,
      `Requests are handled by ${entityName}. We may need to verify your identity before fulfilling a request.`,
    ],
  },
  {
    id: "delete",
    title: "Delete Account",
    paragraphs: [
      "You may request account deletion through available in-product settings or by contacting us when a deletion channel is published.",
      "After deletion, residual copies may remain in backups for a limited period, and we may retain information needed for legal compliance or abuse prevention.",
    ],
  },
  {
    id: "transfers",
    title: "International Transfers",
    paragraphs: [
      "UMTUBA may process data in countries other than where you live. When we transfer personal data internationally, we use appropriate safeguards required by applicable law.",
      `Governing privacy framework details will be finalized with ${governingLaw} and counsel review.`,
    ],
  },
  {
    id: "updates",
    title: "Updates",
    paragraphs: [
      "We may update this Privacy Policy from time to time. We will change the “Last updated” date and provide additional notice when changes are material.",
      "Continued use of the Service after an update means you acknowledge the revised Policy, except where local law requires a different consent process.",
    ],
  },
  {
    id: "contact",
    title: "Contact",
    paragraphs: [
      `Privacy questions and requests: ${legalEmail}.`,
      `Controller/operator (to be confirmed): ${entityName}, ${registeredAddress}.`,
      "This document is a Draft for legal review and is not final legal advice.",
    ],
  },
];
