export type FactCtx = {
  qty?: string;
  materialEn?: string;
  materialAr?: string;
  extrasEn: string[];
  extrasAr: string[];
};

export type ProductKind = {
  id: string;
  test: (t: string) => boolean;
  en: (ctx: FactCtx) => string;
  ar: (ctx: FactCtx) => string;
  useEn: string;
  useAr: string;
};

export const PRODUCT_KINDS: ProductKind[] = [
  {
    id: "makeup_brush",
    test: (t) => /makeup brush|concealer brush|eye brush/.test(t),
    en: (c) => (c.qty ? `${c.qty}-Piece Makeup Brush Set` : "Makeup Brush Set"),
    ar: (c) => (c.qty ? `طقم فرش مكياج – ${c.qty} قطع` : "طقم فرش مكياج"),
    useEn: "makeup application",
    useAr: "تطبيق المكياج",
  },
  {
    id: "garlic_press",
    test: (t) => /garlic press|garlic crusher|garlic masher|garlic squeezer/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Garlic Press` : "Garlic Press"),
    ar: (c) => (c.materialAr ? `كبّاسة ثوم من ${c.materialAr}` : "كبّاسة ثوم"),
    useEn: "mincing garlic",
    useAr: "هرس الثوم",
  },
  {
    id: "car_phone_holder",
    test: (t) =>
      /phone holder|phone mount|phone stand|gravity phone|navigation bracket|cell phone clipper/.test(t) &&
      /car|vent|dash|magnetic|outlet/.test(t),
    en: (c) => (c.materialEn?.includes("Magnetic") ? "Magnetic Car Phone Holder" : "Car Phone Holder"),
    ar: () => "حامل هاتف للسيارة",
    useEn: "holding a phone in the car",
    useAr: "تثبيت الهاتف في السيارة",
  },
  {
    id: "phone_stand",
    test: (t) => /phone stand holder|phone stand|phone holder/.test(t) && !/car|vent|dash/.test(t),
    en: () => "Phone Stand",
    ar: () => "حامل هاتف",
    useEn: "propping up a phone",
    useAr: "إسناد الهاتف",
  },
  {
    id: "wireless_charger",
    test: (t) => /wireless charger|charging station/.test(t),
    en: () => "Wireless Charging Stand",
    ar: () => "حامل شحن لاسلكي",
    useEn: "charging a compatible phone",
    useAr: "شحن هاتف متوافق",
  },
  {
    id: "screen_protector",
    test: (t) => /screen protector|tempered glass|phone film|rear film/.test(t),
    en: () => "Tempered Glass Screen Protector",
    ar: () => "واقي شاشة زجاج مقسّى",
    useEn: "covering a phone screen",
    useAr: "تغطية شاشة الهاتف",
  },
  {
    id: "phone_case",
    test: (t) => /phone case|silicone case|liquid silicone case/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Phone Case` : "Phone Case"),
    ar: (c) => (c.materialAr ? `غطاء هاتف من ${c.materialAr}` : "غطاء هاتف"),
    useEn: "covering a phone",
    useAr: "تغطية الهاتف",
  },
  {
    id: "charging_cable",
    test: (t) => /charging cable|data cable|fast charg/.test(t) && /cable/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Charging Cable` : "Charging Cable"),
    ar: (c) => (c.materialAr ? `كابل شحن من ${c.materialAr}` : "كابل شحن"),
    useEn: "charging or data transfer",
    useAr: "الشحن أو نقل البيانات",
  },
  {
    id: "leather_belt",
    test: (t) => /\bbelt\b/.test(t) && /leather|cowhide|cowskin|buckle/.test(t) && !/watch|bag strap|skirt/.test(t),
    en: () => "Leather Belt",
    ar: () => "حزام جلد",
    useEn: "waist wear",
    useAr: "الارتداء على الخصر",
  },
  {
    id: "watch_strap",
    test: (t) => /watch strap|wrist strap|metal strap|stainless steel strap/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Watch Strap` : "Watch Strap"),
    ar: (c) => (c.materialAr ? `سوار ساعة من ${c.materialAr}` : "سوار ساعة"),
    useEn: "replacing a watch band",
    useAr: "استبدال سوار الساعة",
  },
  {
    id: "hair_clip",
    test: (t) => /hair clip|claw clip|shark clip|hairpin|duckbill clip|bang clip|banana clip/.test(t),
    en: () => "Hair Clip",
    ar: () => "مشبك شعر",
    useEn: "holding hair",
    useAr: "تثبيت الشعر",
  },
  {
    id: "hair_tie",
    test: (t) => /hair tie|hair ring|scrunchie|hair rope|hair band/.test(t),
    en: () => "Hair Tie",
    ar: () => "ربطة شعر",
    useEn: "tying hair",
    useAr: "ربط الشعر",
  },
  {
    id: "ice_mold",
    test: (t) => /ice (cube |tray|mold|maker|bucket)/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Ice Tray` : "Ice Tray"),
    ar: (c) => (c.materialAr ? `قالب ثلج من ${c.materialAr}` : "قالب ثلج"),
    useEn: "freezing ice",
    useAr: "تجميد الثلج",
  },
  {
    id: "sink_strainer",
    test: (t) => /sink drain|hair catcher|strainer|drain filter|filter mesh/.test(t),
    en: () => "Sink Drain Strainer",
    ar: () => "مصفاة تصريف للحوض",
    useEn: "catching debris at the drain",
    useAr: "التقاط الشوائب عند التصريف",
  },
  {
    id: "dumpling_mold",
    test: (t) => /dumpling/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Dumpling Mold` : "Dumpling Mold"),
    ar: (c) => (c.materialAr ? `قالب فطائر من ${c.materialAr}` : "قالب فطائر"),
    useEn: "pressing dumpling wrappers",
    useAr: "كبس عجينة الفطائر",
  },
  {
    id: "usb_cable",
    test: (t) => /usb|network cable|audio cable|cat6|extension cable/.test(t) && /cable/.test(t),
    en: () => "Cable",
    ar: () => "كابل",
    useEn: "connecting or charging",
    useAr: "التوصيل أو الشحن",
  },
  {
    id: "backpack",
    test: (t) => /backpack|rucksack/.test(t) && !/aliexpress|taobao|baby baby/.test(t),
    en: () => "Backpack",
    ar: () => "حقيبة ظهر",
    useEn: "carrying items",
    useAr: "حمل الأغراض",
  },
  {
    id: "eyeliner",
    test: (t) => /eyeliner|eye liner/.test(t),
    en: () => "Eyeliner",
    ar: () => "آيلاينر",
    useEn: "lining the eyes",
    useAr: "تحديد العين",
  },
  {
    id: "mascara",
    test: (t) => /mascara/.test(t),
    en: () => "Mascara",
    ar: () => "ماسكارا",
    useEn: "coating lashes",
    useAr: "تغطية الرموش",
  },
  {
    id: "blush",
    test: (t) => /blush|monochrome nude|monochrome blush/.test(t),
    en: () => "Blush",
    ar: () => "أحمر خدود",
    useEn: "cheek color",
    useAr: "تلوين الخدين",
  },
  {
    id: "eyebrow_pencil",
    test: (t) => /eyebrow pencil/.test(t),
    en: () => "Eyebrow Pencil",
    ar: () => "قلم حواجب",
    useEn: "shaping brows",
    useAr: "تحديد الحواجب",
  },
  {
    id: "makeup_primer",
    test: (t) => /makeup primer|hydrating makeup primer/.test(t),
    en: () => "Makeup Primer",
    ar: () => "برايمر مكياج",
    useEn: "preparing skin before makeup",
    useAr: "تحضير البشرة قبل المكياج",
  },
  {
    id: "nail_file",
    test: (t) => /nail file|manicure set|pedicure/.test(t) && !/dog|pet|foot artifact/.test(t),
    en: () => "Manicure Nail File Set",
    ar: () => "طقم مبرد أظافر",
    useEn: "filing nails",
    useAr: "برد الأظافر",
  },
  {
    id: "storage_tray",
    test: (t) => /tray|storage box|organizer drawer|jewelry storage|cosmetic tray|makeup storage organizer/.test(t),
    en: () => "Storage Tray",
    ar: () => "صينية تخزين",
    useEn: "organizing small items",
    useAr: "تنظيم الأغراض الصغيرة",
  },
  {
    id: "toiletry_bag",
    test: (t) => /toiletry bag|makeup bag|cosmetic bag|wash bag|cosmetic bag organizer/.test(t),
    en: () => "Travel Toiletry Bag",
    ar: () => "حقيبة أدوات تجميل للسفر",
    useEn: "carrying toiletries",
    useAr: "حمل أدوات العناية",
  },
  {
    id: "car_organizer",
    test: (t) => /car (storage|seat|gap|handbag holder|organizer)/.test(t) || /seat gap|seat back pocket/.test(t),
    en: () => "Car Interior Organizer",
    ar: () => "منظّم لمقصورة السيارة",
    useEn: "organizing items in the car",
    useAr: "تنظيم الأغراض داخل السيارة",
  },
  {
    id: "car_seat_cover",
    test: (t) => /seat cover|seat cushion|seat pad|pet car mat|dog car mat|waterproof pad/.test(t) && /car/.test(t),
    en: () => "Car Seat Cover",
    ar: () => "غطاء مقعد سيارة",
    useEn: "covering a car seat",
    useAr: "تغطية مقعد السيارة",
  },
  {
    id: "car_detail_brush",
    test: (t) => /car/.test(t) && /brush|dust removal|interior cleaning|clean brush/.test(t),
    en: () => "Car Interior Cleaning Brush",
    ar: () => "فرشاة تنظيف لمقصورة السيارة",
    useEn: "dusting a car interior",
    useAr: "إزالة الغبار من مقصورة السيارة",
  },
  {
    id: "kitchen_knife",
    test: (t) => /kitchen knife|boning knife|deboning|kitchen cutter|chopper/.test(t),
    en: () => "Kitchen Knife",
    ar: () => "سكين مطبخ",
    useEn: "kitchen cutting",
    useAr: "القطع في المطبخ",
  },
  {
    id: "bottle_opener",
    test: (t) => /bottle opener|kitchen auxiliary scissors/.test(t),
    en: () => "Kitchen Bottle Opener",
    ar: () => "فتّاحة زجاجات للمطبخ",
    useEn: "opening bottles",
    useAr: "فتح الزجاجات",
  },
  {
    id: "seasoning_jar",
    test: (t) => /seasoning jar|lard jar/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Seasoning Jar` : "Seasoning Jar"),
    ar: (c) => (c.materialAr ? `مرطبان بهارات من ${c.materialAr}` : "مرطبان بهارات"),
    useEn: "storing seasoning",
    useAr: "حفظ التوابل",
  },
  {
    id: "spray_bottle",
    test: (t) => /spray bottle/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Spray Bottle` : "Spray Bottle"),
    ar: (c) => (c.materialAr ? `زجاجة رش من ${c.materialAr}` : "زجاجة رش"),
    useEn: "spraying liquid",
    useAr: "رش السائل",
  },
  {
    id: "baking_mat",
    test: (t) => /baking mat|silicone pyramid|cooking mat/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Baking Mat` : "Baking Mat"),
    ar: (c) => (c.materialAr ? `سجادة خَبز من ${c.materialAr}` : "سجادة خَبز"),
    useEn: "baking or cooking",
    useAr: "الخَبز أو الطبخ",
  },
  {
    id: "baking_mold",
    test: (t) => /baking mold|bread baking|baking bowl/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Baking Mold` : "Baking Mold"),
    ar: (c) => (c.materialAr ? `قالب خَبز من ${c.materialAr}` : "قالب خَبز"),
    useEn: "shaping baked goods",
    useAr: "تشكيل المخبوزات",
  },
  {
    id: "baking_scale",
    test: (t) => /baking scale/.test(t),
    en: () => "Kitchen Baking Scale",
    ar: () => "ميزان خَبز للمطبخ",
    useEn: "weighing ingredients",
    useAr: "وزن المكوّنات",
  },
  {
    id: "cupcake_liner",
    test: (t) => /cupcake liner|baking cups/.test(t),
    en: (c) => (c.qty ? `${c.qty}-Piece Cupcake Liners` : "Cupcake Liners"),
    ar: (c) => (c.qty ? `قوالب كب كيك – ${c.qty} قطع` : "قوالب كب كيك"),
    useEn: "lining cupcakes",
    useAr: "تبطين الكب كيك",
  },
  {
    id: "spatula_set",
    test: (t) => /spatula|silicone scraper|kitchenware .*piece/.test(t),
    en: (c) => (c.qty ? `${c.qty}-Piece Silicone Kitchen Utensil Set` : "Silicone Kitchen Utensil"),
    ar: (c) => (c.qty ? `طقم أدوات مطبخ سيليكون – ${c.qty} قطع` : "أداة مطبخ من السيليكون"),
    useEn: "cooking or baking",
    useAr: "الطبخ أو الخَبز",
  },
  {
    id: "pajama",
    test: (t) => /pajama|homewear|nightdress|nightgown|bathrobe/.test(t),
    en: () => "Sleepwear Set",
    ar: () => "طقم ملابس نوم",
    useEn: "sleeping or home wear",
    useAr: "النوم أو الارتداء في المنزل",
  },
  {
    id: "neck_pillow",
    test: (t) => /neck pillow|u-shape|u-shaped pillow|u shape/.test(t) && !/cat |dog |puppy|kitten|pet /.test(t),
    en: () => "Travel Neck Pillow",
    ar: () => "وسادة رقبة للسفر",
    useEn: "supporting the neck while traveling",
    useAr: "دعم الرقبة أثناء السفر",
  },
  {
    id: "travel_bag",
    test: (t) => /travel bag|garment bag|duffle|luggage bag|carry-on luggage/.test(t),
    en: () => "Travel Bag",
    ar: () => "حقيبة سفر",
    useEn: "carrying clothes while traveling",
    useAr: "حمل الملابس أثناء السفر",
  },
  {
    id: "luggage_cover",
    test: (t) => /luggage protection cover|luggage moving|dustproof storage bag/.test(t),
    en: () => "Luggage Cover",
    ar: () => "غطاء حقيبة سفر",
    useEn: "covering luggage",
    useAr: "تغطية حقيبة السفر",
  },
  {
    id: "compression_backpack",
    test: (t) => /vacuum compression backpack|compression backpack/.test(t),
    en: () => "Compression Backpack",
    ar: () => "حقيبة ظهر ضاغطة",
    useEn: "packing items more tightly",
    useAr: "تعبئة الأغراض بشكل أضيق",
  },
  {
    id: "perfume_bottle",
    test: (t) => /perfume bottle|perfume dispensing/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Perfume Bottle` : "Perfume Bottle"),
    ar: (c) => (c.materialAr ? `زجاجة عطر من ${c.materialAr}` : "زجاجة عطر"),
    useEn: "holding perfume",
    useAr: "حفظ العطر",
  },
  {
    id: "squeeze_bottle",
    test: (t) => /silica gel packaging bottle|squeeze type/.test(t),
    en: () => "Squeeze Travel Bottle",
    ar: () => "زجاجة ضغط للسفر",
    useEn: "carrying liquids while traveling",
    useAr: "حمل السوائل أثناء السفر",
  },
  {
    id: "glasses_case",
    test: (t) => /glasses case/.test(t),
    en: () => "Folding Glasses Case",
    ar: () => "علبة نظارات قابلة للطي",
    useEn: "protecting glasses",
    useAr: "حماية النظارات",
  },
  {
    id: "night_light",
    test: (t) => /night lamp|night light|bedside lamp|wax lamp|table lamp|desk lamp/.test(t),
    en: () => "Small Night Light",
    ar: () => "إضاءة ليلية صغيرة",
    useEn: "low lighting at night",
    useAr: "إضاءة خافتة ليلاً",
  },
  {
    id: "stool",
    test: (t) => /small stool|small bench|stackable dice/.test(t),
    en: () => "Stackable Small Stool",
    ar: () => "كرسي صغير قابل للتكديس",
    useEn: "sitting or stepping",
    useAr: "الجلوس أو الارتقاء",
  },
  {
    id: "yoga_shorts",
    test: (t) => /yoga shorts|gym yoga|running shorts/.test(t),
    en: () => "Yoga Workout Shorts",
    ar: () => "شورت يوغا للتمرين",
    useEn: "workout wear",
    useAr: "الارتداء أثناء التمرين",
  },
  {
    id: "silk_scarf",
    test: (t) => /silk scarf|shawl|simulation silk scarf/.test(t),
    en: () => "Silk Scarf",
    ar: () => "وشاح حرير",
    useEn: "wearing around the neck or shoulders",
    useAr: "الارتداء حول العنق أو الكتفين",
  },
  {
    id: "pillowcase",
    test: (t) => /pillowcase|ice silk pillowcase/.test(t),
    en: () => "Satin Pillowcase",
    ar: () => "كيس وسادة ساتان",
    useEn: "covering a pillow",
    useAr: "تغطية الوسادة",
  },
  {
    id: "casual_pants",
    test: (t) => /casual pants|ice silk casual/.test(t),
    en: () => "Casual Pants",
    ar: () => "بنطلون كاجوال",
    useEn: "everyday wear",
    useAr: "الارتداء اليومي",
  },
  {
    id: "kids_hat",
    test: (t) => /waffle hat|beret hat|fisherman hat|kids.*hat|baby.*hat/.test(t),
    en: () => "Kids Hat",
    ar: () => "قبعة أطفال",
    useEn: "head wear for children",
    useAr: "تغطية رأس الطفل",
  },
  {
    id: "kids_sweater",
    test: (t) => /kids knitted|girls long sleeve|knit lace sweater/.test(t),
    en: () => "Kids Knit Sweater",
    ar: () => "كنزة تريكو للأطفال",
    useEn: "children's wear",
    useAr: "ملابس الأطفال",
  },
  {
    id: "kids_swimsuit",
    test: (t) => /swimsuit kids|kids clothes two-piece/.test(t),
    en: () => "Kids Two-Piece Swimsuit",
    ar: () => "ملابس سباحة قطعتان للأطفال",
    useEn: "children's swim wear",
    useAr: "السباحة للأطفال",
  },
  {
    id: "wallet",
    test: (t) => /wallet|zero wallet|coin package/.test(t),
    en: () => "Wallet",
    ar: () => "محفظة",
    useEn: "carrying cards or coins",
    useAr: "حمل البطاقات أو النقود",
  },
  {
    id: "tie_clip",
    test: (t) => /tie clip|note tie clip/.test(t),
    en: () => "Tie Clip",
    ar: () => "مشبك ربطة عنق",
    useEn: "holding a tie",
    useAr: "تثبيت ربطة العنق",
  },
  {
    id: "cat_toy",
    test: (t) => /cat toy|catnip|feather wand|cat teaser|claw sharpener|cat laser/.test(t),
    en: () => "Cat Toy",
    ar: () => "لعبة قطط",
    useEn: "play for cats",
    useAr: "لعب القطط",
  },
  {
    id: "pet_food_spoon",
    test: (t) => /pet food spoon|cat food spoon/.test(t),
    en: () => "Pet Food Scoop",
    ar: () => "مغرفة طعام للحيوانات الأليفة",
    useEn: "scooping pet food",
    useAr: "غرف طعام الحيوانات الأليفة",
  },
  {
    id: "litter_scoop",
    test: (t) => /litter scoop|cat toilet cleaning/.test(t),
    en: () => "Cat Litter Scoop",
    ar: () => "مجرفة رمل القطط",
    useEn: "scooping cat litter",
    useAr: "غرف رمل القطط",
  },
  {
    id: "dog_food_bag",
    test: (t) => /dog food storage bag/.test(t),
    en: () => "Dog Food Storage Bag",
    ar: () => "كيس تخزين طعام الكلاب",
    useEn: "storing dog food",
    useAr: "حفظ طعام الكلاب",
  },
  {
    id: "poop_bag",
    test: (t) => /poop bag|waste bag dispenser|pet waste bag/.test(t),
    en: () => "Pet Waste Bag Dispenser",
    ar: () => "حامل أكياس مخلفات الحيوانات الأليفة",
    useEn: "holding pet waste bags",
    useAr: "حمل أكياس المخلفات",
  },
  {
    id: "pet_bowl",
    test: (t) => /pet bowl|cat double bowls|slow feeder|food bowl/.test(t) && /pet|cat|dog/.test(t),
    en: () => "Pet Food Bowl",
    ar: () => "وعاء طعام للحيوانات الأليفة",
    useEn: "feeding pets",
    useAr: "إطعام الحيوانات الأليفة",
  },
  {
    id: "licking_mat",
    test: (t) => /licking pad|licking mat|smelling mat/.test(t),
    en: (c) => (c.materialEn ? `${c.materialEn} Pet Licking Mat` : "Pet Licking Mat"),
    ar: (c) => (c.materialAr ? `سجادة لعق من ${c.materialAr}` : "سجادة لعق للحيوانات الأليفة"),
    useEn: "slow feeding or licking",
    useAr: "اللعق أو الأكل البطيء",
  },
  {
    id: "pet_mat",
    test: (t) => /pet mat|dog mat|cat mat|pet blanket|pet placemat/.test(t),
    en: () => "Pet Mat",
    ar: () => "سجادة للحيوانات الأليفة",
    useEn: "a resting or feeding surface for pets",
    useAr: "سطح راحة أو طعام للحيوانات الأليفة",
  },
  {
    id: "squeeze_toy",
    test: (t) => /squeezing toy|slow rebound|decompression toy/.test(t),
    en: () => "Squeeze Toy",
    ar: () => "لعبة ضغط",
    useEn: "squeezing by hand",
    useAr: "الضغط باليد",
  },
  {
    id: "fidget_spinner",
    test: (t) => /fidget spinner|finger spinner/.test(t),
    en: () => "Fidget Spinner",
    ar: () => "سبينر يدوي",
    useEn: "spinning in the hand",
    useAr: "التدوير باليد",
  },
  {
    id: "sensory_ball",
    test: (t) => /sensory ball|worry ball/.test(t),
    en: () => "Silicone Sensory Ball",
    ar: () => "كرة حسية من السيليكون",
    useEn: "hand play",
    useAr: "اللعب باليد",
  },
  {
    id: "stroller_cover",
    test: (t) => /stroller windshield|stroller.*cover|rain cover/.test(t),
    en: () => "Stroller Rain Cover",
    ar: () => "غطاء مطر لعربة الأطفال",
    useEn: "covering a stroller in weather",
    useAr: "تغطية عربة الأطفال في الطقس",
  },
  {
    id: "play_mat",
    test: (t) => /crawling mat|cloud carpet|baby game/.test(t),
    en: () => "Baby Play Mat",
    ar: () => "سجادة لعب للأطفال",
    useEn: "a floor surface for play",
    useAr: "سطح أرضي للعب",
  },
  {
    id: "foldable_toilet",
    test: (t) => /foldable toilet|children's foldable toilet/.test(t),
    en: () => "Foldable Children's Toilet",
    ar: () => "مرحاض أطفال قابل للطي",
    useEn: "a portable child's toilet",
    useAr: "مرحاض محمول للطفل",
  },
  {
    id: "cable_clip",
    test: (t) => /cable clip|cord holder|cable management|wire organizer|wire keeper/.test(t),
    en: () => "Cable Management Clip",
    ar: () => "مشبك لتنظيم الكابلات",
    useEn: "holding cables in place",
    useAr: "تثبيت الكابلات في موضعها",
  },
  {
    id: "drawer_box",
    test: (t) => /drawer gift box/.test(t),
    en: () => "Drawer Gift Box",
    ar: () => "علبة هدايا بدرج",
    useEn: "storing or gifting small items",
    useAr: "حفظ الأغراض الصغيرة أو إهداؤها",
  },
];
