import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  BRAND,
  DEFAULT_DESCRIPTION,
  DEFAULT_TITLE,
  TITLE_TEMPLATE,
} from "./brand";
import { ROBOTS_DISALLOW_PATHS, SITEMAP_STATIC_ROUTES } from "./indexing";
import {
  buildPageMetadata,
  buildPublicProfileMetadata,
  buildRootMetadata,
  isSafePublicShareImageUrl,
} from "./metadata";

const ROOT = process.cwd();

function walkSourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (
      entry.name === "node_modules" ||
      entry.name === ".next" ||
      entry.name === ".git"
    ) {
      continue;
    }
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walkSourceFiles(full, acc);
    } else if (
      /\.(tsx?|jsx?|mjs|cjs|json)$/.test(entry.name) &&
      !/\.test\.(tsx?|jsx?)$/.test(entry.name)
    ) {
      acc.push(full);
    }
  }
  return acc;
}

describe("global brand metadata", () => {
  it("uses UMTUBA title template and default description", () => {
    const root = buildRootMetadata({
      NEXT_PUBLIC_SITE_URL: "https://umtuba.com",
      NODE_ENV: "production",
    });
    expect(root.title).toEqual({
      default: DEFAULT_TITLE,
      template: TITLE_TEMPLATE,
    });
    expect(root.description).toBe(DEFAULT_DESCRIPTION);
    expect(root.applicationName).toBe(BRAND.name);
    expect(root.metadataBase?.toString()).toBe("https://umtuba.com/");
    expect(DEFAULT_DESCRIPTION).toContain(BRAND.tagline);
    expect(DEFAULT_DESCRIPTION).toContain(BRAND.taglineAr);
    expect(DEFAULT_DESCRIPTION).toContain(BRAND.mission);
  });

  it("leaves no Create Next App copy in app metadata config", () => {
    const files = [
      join(ROOT, "app/layout.tsx"),
      join(ROOT, "lib/site/brand.ts"),
      join(ROOT, "lib/site/metadata.ts"),
      join(ROOT, "lib/site/routeMetadata.ts"),
      join(ROOT, "app/manifest.ts"),
      join(ROOT, "app/robots.ts"),
      join(ROOT, "app/sitemap.ts"),
    ];
    for (const file of files) {
      const text = readFileSync(file, "utf8");
      expect(text).not.toMatch(/Create Next App/i);
      expect(text).not.toMatch(/Generated by create next app/i);
    }
  });
});

describe("route robots / sitemap policy", () => {
  it("marks private and auth routes noindex", () => {
    const privatePaths = [
      "/login",
      "/signup",
      "/forgot-password",
      "/auth/update-password",
      "/settings",
      "/messages",
      "/notifications",
      "/rewards",
      "/saved",
      "/create/video",
    ];
    for (const path of privatePaths) {
      const meta = buildPageMetadata({
        title: "t",
        description: "d",
        path,
        index: "noindex",
      });
      expect(meta.robots).toMatchObject({ index: false, follow: false });
    }

    for (const path of ROBOTS_DISALLOW_PATHS) {
      expect(
        path.startsWith("/login") ||
          path.startsWith("/signup") ||
          path.startsWith("/register") ||
          path.startsWith("/forgot-password") ||
          path.startsWith("/auth") ||
          path.startsWith("/settings") ||
          path.startsWith("/messages") ||
          path.startsWith("/notifications") ||
          path.startsWith("/create") ||
          path.startsWith("/saved") ||
          path.startsWith("/rewards") ||
          path.startsWith("/creator") ||
          path.startsWith("/feed") ||
          path.startsWith("/journey-pro") ||
          path.startsWith("/city") ||
          path.startsWith("/live/media-lab")
      ).toBe(true);
    }
  });

  it("sitemap includes only public static routes", () => {
    expect([...SITEMAP_STATIC_ROUTES]).toEqual([
      "/",
      "/discover",
      "/live",
      "/watch",
      "/post-journey",
      "/terms",
      "/privacy",
      "/account-deletion",
    ]);
    const blocked = [
      "/login",
      "/messages",
      "/settings",
      "/feed",
      "/journey-pro",
      "/city",
      "/rewards",
      "/live/media-lab",
    ];
    for (const path of blocked) {
      expect(SITEMAP_STATIC_ROUTES).not.toContain(path);
    }
  });

  it("buildPageMetadata sets canonical and OG image dimensions", () => {
    const meta = buildPageMetadata({
      title: "Discover",
      description: "desc",
      path: "/discover",
      index: "index",
    });
    expect(meta.alternates?.canonical).toBe("/discover");
    const images = meta.openGraph?.images;
    expect(Array.isArray(images)).toBe(true);
    const first = Array.isArray(images) ? images[0] : null;
    if (!first || typeof first === "string" || first instanceof URL) {
      throw new Error("expected OG image object");
    }
    expect(first.url).toBe("/opengraph-image");
    expect(first.width).toBe(1200);
    expect(first.height).toBe(630);
    expect(first.alt).toContain(BRAND.name);
  });
});

describe("public profile metadata", () => {
  it("uses display name, username, and bio only", () => {
    const meta = buildPublicProfileMetadata({
      username: "ada",
      displayName: "Ada Lovelace",
      bio: "Inventor of programs",
      avatarUrl: "https://cdn.example.com/avatars/ada.png",
    });
    expect(meta.title).toBe("Ada Lovelace (@ada)");
    expect(meta.description).toBe("Inventor of programs");
    expect(meta.alternates?.canonical).toBe("/profile/ada");
    const serialized = JSON.stringify(meta);
    expect(serialized).not.toMatch(/um points/i);
    expect(serialized).not.toMatch(/@private@email/i);
    expect(serialized).not.toMatch(/hidden.?location/i);
  });

  it("omits location and reward fields from the public metadata shape", () => {
    const meta = buildPublicProfileMetadata({
      username: "bob",
      displayName: "Bob",
      bio: "Hello from the community",
      avatarUrl: null,
    });
    const serialized = JSON.stringify(meta);
    expect(serialized).toContain("Hello from the community");
    expect(serialized).not.toMatch(/um.?points/i);
    expect(serialized).not.toMatch(/email/i);
    expect(serialized).not.toMatch(/"city"/i);
    expect(serialized).not.toMatch(/"country"/i);
  });

  it("handles missing profile safely with noindex", () => {
    const meta = buildPublicProfileMetadata(null);
    expect(meta.robots).toMatchObject({ index: false });
    expect(String(meta.title)).toMatch(/not found/i);
  });

  it("rejects signed avatar URLs for share images", () => {
    expect(
      isSafePublicShareImageUrl(
        "https://storage.example.com/a.png?token=abc&Expires=123"
      )
    ).toBe(false);
    expect(
      isSafePublicShareImageUrl("https://storage.example.com/a.png")
    ).toBe(true);
    const meta = buildPublicProfileMetadata({
      username: "ada",
      avatarUrl:
        "https://storage.example.com/a.png?X-Amz-Signature=deadbeef",
    });
    const images = meta.openGraph?.images;
    const first = Array.isArray(images) ? images[0] : null;
    if (!first || typeof first === "string" || first instanceof URL) {
      throw new Error("expected OG image object");
    }
    expect(first.url).toBe("/opengraph-image");
  });
});

describe("source hygiene", () => {
  it("does not leave Create Next App in lib/site or app metadata entrypoints", () => {
    const roots = [join(ROOT, "lib/site"), join(ROOT, "app")];
    const hits: string[] = [];
    for (const root of roots) {
      for (const file of walkSourceFiles(root)) {
        if (file.includes(`${join("app", "data")}`)) continue;
        const text = readFileSync(file, "utf8");
        if (/Create Next App/i.test(text) || /Generated by create next app/i.test(text)) {
          hits.push(file);
        }
      }
    }
    expect(hits).toEqual([]);
  });
});
