/**
 * UMTUBA Unified Page Registry V1 — canonical inventory of App Router pages.
 * Generated from discovered app page.tsx files. Do not invent routes.
 */

import type { PageOverlapNote, PageRegistryEntry } from "./types";

export const PAGE_REGISTRY: readonly PageRegistryEntry[] = [
  {
    id: "admin.ads.advertisers",
    path: "/admin/ads/advertisers",
    title: "Admin · Ads · Advertisers",
    description: "App Router page at /admin/ads/advertisers",
    domain: "admin",
    section: "ads",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ads",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ads/advertisers/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ads.campaigns",
    path: "/admin/ads/campaigns",
    title: "Admin · Ads · Campaigns",
    description: "App Router page at /admin/ads/campaigns",
    domain: "admin",
    section: "ads",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ads",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ads/campaigns/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ads.creatives",
    path: "/admin/ads/creatives",
    title: "Admin · Ads · Creatives",
    description: "App Router page at /admin/ads/creatives",
    domain: "admin",
    section: "ads",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ads",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ads/creatives/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ads.diagnostics",
    path: "/admin/ads/diagnostics",
    title: "Admin · Ads · Diagnostics",
    description: "App Router page at /admin/ads/diagnostics",
    domain: "admin",
    section: "ads",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ads",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ads/diagnostics/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ads",
    path: "/admin/ads",
    title: "Admin · Ads",
    description: "App Router page at /admin/ads",
    domain: "admin",
    section: "ads",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ads/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ads.reviews",
    path: "/admin/ads/reviews",
    title: "Admin · Ads · Reviews",
    description: "App Router page at /admin/ads/reviews",
    domain: "admin",
    section: "ads",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ads",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ads/reviews/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.audit",
    path: "/admin/ai-data/audit",
    title: "Admin · Ai Data · Audit",
    description: "App Router page at /admin/ai-data/audit",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/audit/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.datasets",
    path: "/admin/ai-data/datasets",
    title: "Admin · Ai Data · Datasets",
    description: "App Router page at /admin/ai-data/datasets",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/datasets/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.evaluation-sets",
    path: "/admin/ai-data/evaluation-sets",
    title: "Admin · Ai Data · Evaluation Sets",
    description: "App Router page at /admin/ai-data/evaluation-sets",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/evaluation-sets/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.experiments",
    path: "/admin/ai-data/experiments",
    title: "Admin · Ai Data · Experiments",
    description: "App Router page at /admin/ai-data/experiments",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/experiments/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.models",
    path: "/admin/ai-data/models",
    title: "Admin · Ai Data · Models",
    description: "App Router page at /admin/ai-data/models",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/models/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data",
    path: "/admin/ai-data",
    title: "Admin · Ai Data",
    description: "App Router page at /admin/ai-data",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.promotion",
    path: "/admin/ai-data/promotion",
    title: "Admin · Ai Data · Promotion",
    description: "App Router page at /admin/ai-data/promotion",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/promotion/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.review",
    path: "/admin/ai-data/review",
    title: "Admin · Ai Data · Review",
    description: "App Router page at /admin/ai-data/review",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/review/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai-data.versions",
    path: "/admin/ai-data/versions",
    title: "Admin · Ai Data · Versions",
    description: "App Router page at /admin/ai-data/versions",
    domain: "ai",
    section: "ai-data",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.ai-data",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai-data/versions/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.ai",
    path: "/admin/ai",
    title: "Admin · Ai",
    description: "App Router page at /admin/ai",
    domain: "ai",
    section: "ai-diagnostics",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/ai/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.classification",
    path: "/admin/knowledge/classification",
    title: "Admin · Knowledge · Classification",
    description: "App Router page at /admin/knowledge/classification",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/classification/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.datasets",
    path: "/admin/knowledge/datasets",
    title: "Admin · Knowledge · Datasets",
    description: "App Router page at /admin/knowledge/datasets",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/datasets/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.eligibility",
    path: "/admin/knowledge/eligibility",
    title: "Admin · Knowledge · Eligibility",
    description: "App Router page at /admin/knowledge/eligibility",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/eligibility/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.history",
    path: "/admin/knowledge/history",
    title: "Admin · Knowledge · History",
    description: "App Router page at /admin/knowledge/history",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/history/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge",
    path: "/admin/knowledge",
    title: "Admin · Knowledge",
    description: "App Router page at /admin/knowledge",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.quality",
    path: "/admin/knowledge/quality",
    title: "Admin · Knowledge · Quality",
    description: "App Router page at /admin/knowledge/quality",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/quality/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.rights",
    path: "/admin/knowledge/rights",
    title: "Admin · Knowledge · Rights",
    description: "App Router page at /admin/knowledge/rights",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/rights/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.knowledge.sources",
    path: "/admin/knowledge/sources",
    title: "Admin · Knowledge · Sources",
    description: "App Router page at /admin/knowledge/sources",
    domain: "ai",
    section: "knowledge",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.knowledge",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/knowledge/sources/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.platform.pages",
    path: "/admin/platform/pages",
    title: "Admin · Platform · Pages",
    description: "App Router page at /admin/platform/pages",
    domain: "admin",
    section: "platform",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/platform/pages/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.capabilities",
    path: "/admin/private-ai/capabilities",
    title: "Admin · Private Ai · Capabilities",
    description: "App Router page at /admin/private-ai/capabilities",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/capabilities/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.deployments",
    path: "/admin/private-ai/deployments",
    title: "Admin · Private Ai · Deployments",
    description: "App Router page at /admin/private-ai/deployments",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/deployments/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.hardware",
    path: "/admin/private-ai/hardware",
    title: "Admin · Private Ai · Hardware",
    description: "App Router page at /admin/private-ai/hardware",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/hardware/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.lifecycle",
    path: "/admin/private-ai/lifecycle",
    title: "Admin · Private Ai · Lifecycle",
    description: "App Router page at /admin/private-ai/lifecycle",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/lifecycle/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.models",
    path: "/admin/private-ai/models",
    title: "Admin · Private Ai · Models",
    description: "App Router page at /admin/private-ai/models",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/models/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai",
    path: "/admin/private-ai",
    title: "Admin · Private Ai",
    description: "App Router page at /admin/private-ai",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.routing",
    path: "/admin/private-ai/routing",
    title: "Admin · Private Ai · Routing",
    description: "App Router page at /admin/private-ai/routing",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/routing/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.private-ai.runtime",
    path: "/admin/private-ai/runtime",
    title: "Admin · Private Ai · Runtime",
    description: "App Router page at /admin/private-ai/runtime",
    domain: "ai",
    section: "private-ai",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.private-ai",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/private-ai/runtime/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.store",
    path: "/admin/store",
    title: "Admin · Store",
    description: "App Router page at /admin/store",
    domain: "admin",
    section: "store",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/store/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.store.products",
    path: "/admin/store/products",
    title: "Admin · Store · Products",
    description: "App Router page at /admin/store/products",
    domain: "admin",
    section: "store",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/store/products/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.store.reservations",
    path: "/admin/store/reservations",
    title: "Admin · Store · Reservations",
    description: "App Router page at /admin/store/reservations",
    domain: "admin",
    section: "store",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/store/reservations/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "admin.store.sellers",
    path: "/admin/store/sellers",
    title: "Admin · Store · Sellers",
    description: "App Router page at /admin/store/sellers",
    domain: "admin",
    section: "store",
    audience: "admin",
    access: "admin",
    navigationVisibility: "utility",
    adminOnly: true,
    authenticated: true,
    dynamic: false,
    parentId: "admin.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/admin/store/sellers/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.apply",
    path: "/advertise/apply",
    title: "Advertise · Apply",
    description: "App Router page at /advertise/apply",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "advertise",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/apply/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.campaigns.by-campaignid",
    path: "/advertise/campaigns/[campaignId]",
    title: "Advertise · Campaigns · campaignId",
    description: "App Router page at /advertise/campaigns/[campaignId]",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "advertise.campaigns",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/campaigns/[campaignId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.campaigns.new",
    path: "/advertise/campaigns/new",
    title: "Advertise · Campaigns · New",
    description: "App Router page at /advertise/campaigns/new",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "advertise.campaigns",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/campaigns/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.campaigns",
    path: "/advertise/campaigns",
    title: "Advertise · Campaigns",
    description: "App Router page at /advertise/campaigns",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "advertise",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/campaigns/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.creatives.new",
    path: "/advertise/creatives/new",
    title: "Advertise · Creatives · New",
    description: "App Router page at /advertise/creatives/new",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "advertise",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/creatives/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.dashboard",
    path: "/advertise/dashboard",
    title: "Advertise · Dashboard",
    description: "App Router page at /advertise/dashboard",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "advertise",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/dashboard/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise",
    path: "/advertise",
    title: "Advertise",
    description: "App Router page at /advertise",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "advertise.settings",
    path: "/advertise/settings",
    title: "Advertise · Settings",
    description: "App Router page at /advertise/settings",
    domain: "commerce",
    section: "advertise",
    audience: "advertiser",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "advertise",
    legacy: false,
    deprecated: false,
    sourceFile: "app/advertise/settings/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "ai-hub.assistant",
    path: "/ai-hub/assistant",
    title: "Ai Hub · Assistant",
    description: "App Router page at /ai-hub/assistant",
    domain: "ai",
    section: "hub",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "ai-hub",
    legacy: false,
    deprecated: false,
    sourceFile: "app/ai-hub/assistant/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "ai-hub",
    path: "/ai-hub",
    title: "Ai Hub",
    description: "App Router page at /ai-hub",
    domain: "ai",
    section: "hub",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/ai-hub/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "articles.by-articleid",
    path: "/articles/[articleId]",
    title: "Articles · articleId",
    description: "App Router page at /articles/[articleId]",
    domain: "content",
    section: "articles",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/articles/[articleId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "auth.update-password",
    path: "/auth/update-password",
    title: "Auth · Update Password",
    description: "App Router page at /auth/update-password",
    domain: "identity",
    section: "auth",
    audience: "public",
    access: "public",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/auth/update-password/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "city.by-cityslug",
    path: "/city/[citySlug]",
    title: "City · citySlug",
    description: "App Router page at /city/[citySlug]",
    domain: "platform",
    section: "city-prototype",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "platform.home",
    legacy: true,
    deprecated: false,
    sourceFile: "app/city/[citySlug]/page.tsx",
    status: "legacy",
    orphan: true,
  },
  {
    id: "create.article",
    path: "/create/article",
    title: "Create · Article",
    description: "App Router page at /create/article",
    domain: "content",
    section: "create",
    audience: "creator",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/create/article/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "create.video",
    path: "/create/video",
    title: "Create · Video",
    description: "App Router page at /create/video",
    domain: "content",
    section: "create",
    audience: "creator",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/create/video/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "creator.insights",
    path: "/creator/insights",
    title: "Creator · Insights",
    description: "App Router page at /creator/insights",
    domain: "ai",
    section: "creator-insights",
    audience: "creator",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/creator/insights/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "discover",
    path: "/discover",
    title: "Discover",
    description: "App Router page at /discover",
    domain: "platform",
    section: "home-alias",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: true,
    deprecated: false,
    sourceFile: "app/discover/page.tsx",
    status: "legacy",
    orphan: false,
  },
  {
    id: "feed",
    path: "/feed",
    title: "Feed",
    description: "App Router page at /feed",
    domain: "content",
    section: "feed",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: true,
    deprecated: false,
    sourceFile: "app/feed/page.tsx",
    status: "legacy",
    orphan: true,
  },
  {
    id: "forgot-password",
    path: "/forgot-password",
    title: "Forgot Password",
    description: "App Router page at /forgot-password",
    domain: "identity",
    section: "auth",
    audience: "public",
    access: "public",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/forgot-password/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "games",
    path: "/games",
    title: "Games",
    description: "App Router page at /games",
    domain: "platform",
    section: "games",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/games/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "invite.by-code",
    path: "/invite/[code]",
    title: "Invite · code",
    description: "App Router page at /invite/[code]",
    domain: "platform",
    section: "invite",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/invite/[code]/page.tsx",
    status: "active",
    orphan: true,
  },
  {
    id: "journey-pro",
    path: "/journey-pro",
    title: "Journey Pro",
    description: "App Router page at /journey-pro",
    domain: "content",
    section: "journey",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: true,
    deprecated: false,
    sourceFile: "app/journey-pro/page.tsx",
    status: "legacy",
    orphan: true,
  },
  {
    id: "learning.activities.by-activityid.assessment-attempts.by-attemptid",
    path: "/learning/activities/[activityId]/assessment-attempts/[attemptId]",
    title: "Learning · Activities · activityId · Assessment Attempts · attemptId",
    description: "App Router page at /learning/activities/[activityId]/assessment-attempts/[attemptId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.activities.by-activityid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/activities/[activityId]/assessment-attempts/[attemptId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.activities.by-activityid.assessment",
    path: "/learning/activities/[activityId]/assessment",
    title: "Learning · Activities · activityId · Assessment",
    description: "App Router page at /learning/activities/[activityId]/assessment",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.activities.by-activityid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/activities/[activityId]/assessment/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.activities.by-activityid.assignment",
    path: "/learning/activities/[activityId]/assignment",
    title: "Learning · Activities · activityId · Assignment",
    description: "App Router page at /learning/activities/[activityId]/assignment",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.activities.by-activityid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/activities/[activityId]/assignment/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.activities.by-activityid.lab",
    path: "/learning/activities/[activityId]/lab",
    title: "Learning · Activities · activityId · Lab",
    description: "App Router page at /learning/activities/[activityId]/lab",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.activities.by-activityid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/activities/[activityId]/lab/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.activities.by-activityid",
    path: "/learning/activities/[activityId]",
    title: "Learning · Activities · activityId",
    description: "App Router page at /learning/activities/[activityId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/activities/[activityId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.activities.by-activityid.project",
    path: "/learning/activities/[activityId]/project",
    title: "Learning · Activities · activityId · Project",
    description: "App Router page at /learning/activities/[activityId]/project",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.activities.by-activityid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/activities/[activityId]/project/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.attempts.by-attemptid",
    path: "/learning/attempts/[attemptId]",
    title: "Learning · Attempts · attemptId",
    description: "App Router page at /learning/attempts/[attemptId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/attempts/[attemptId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.catalog.by-courseslug",
    path: "/learning/catalog/[courseSlug]",
    title: "Learning · Catalog · courseSlug",
    description: "App Router page at /learning/catalog/[courseSlug]",
    domain: "learning",
    section: "catalog",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "learning.catalog",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/catalog/[courseSlug]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.catalog",
    path: "/learning/catalog",
    title: "Learning · Catalog",
    description: "App Router page at /learning/catalog",
    domain: "learning",
    section: "catalog",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/catalog/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.calendar",
    path: "/learning/courses/[courseId]/calendar",
    title: "Learning · Courses · courseId · Calendar",
    description: "App Router page at /learning/courses/[courseId]/calendar",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/calendar/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.community.announcements",
    path: "/learning/courses/[courseId]/community/announcements",
    title: "Learning · Courses · courseId · Community · Announcements",
    description: "App Router page at /learning/courses/[courseId]/community/announcements",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid.community",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/community/announcements/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.community.discussions.by-threadid",
    path: "/learning/courses/[courseId]/community/discussions/[threadId]",
    title: "Learning · Courses · courseId · Community · Discussions · threadId",
    description: "App Router page at /learning/courses/[courseId]/community/discussions/[threadId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid.community.discussions",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/community/discussions/[threadId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.community.discussions",
    path: "/learning/courses/[courseId]/community/discussions",
    title: "Learning · Courses · courseId · Community · Discussions",
    description: "App Router page at /learning/courses/[courseId]/community/discussions",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid.community",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/community/discussions/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.community",
    path: "/learning/courses/[courseId]/community",
    title: "Learning · Courses · courseId · Community",
    description: "App Router page at /learning/courses/[courseId]/community",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/community/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.community.qa.by-questionid",
    path: "/learning/courses/[courseId]/community/qa/[questionId]",
    title: "Learning · Courses · courseId · Community · Qa · questionId",
    description: "App Router page at /learning/courses/[courseId]/community/qa/[questionId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid.community.qa",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/community/qa/[questionId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.community.qa",
    path: "/learning/courses/[courseId]/community/qa",
    title: "Learning · Courses · courseId · Community · Qa",
    description: "App Router page at /learning/courses/[courseId]/community/qa",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid.community",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/community/qa/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.live.by-sessionid",
    path: "/learning/courses/[courseId]/live/[sessionId]",
    title: "Learning · Courses · courseId · Live · sessionId",
    description: "App Router page at /learning/courses/[courseId]/live/[sessionId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid.live",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/live/[sessionId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.live",
    path: "/learning/courses/[courseId]/live",
    title: "Learning · Courses · courseId · Live",
    description: "App Router page at /learning/courses/[courseId]/live",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/live/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid",
    path: "/learning/courses/[courseId]",
    title: "Learning · Courses · courseId",
    description: "App Router page at /learning/courses/[courseId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.progress",
    path: "/learning/courses/[courseId]/progress",
    title: "Learning · Courses · courseId · Progress",
    description: "App Router page at /learning/courses/[courseId]/progress",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/progress/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.courses.by-courseid.resources",
    path: "/learning/courses/[courseId]/resources",
    title: "Learning · Courses · courseId · Resources",
    description: "App Router page at /learning/courses/[courseId]/resources",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/courses/[courseId]/resources/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.bootstrap",
    path: "/learning/instructor/bootstrap",
    title: "Learning · Instructor · Bootstrap",
    description: "App Router page at /learning/instructor/bootstrap",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "learning.instructor",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/bootstrap/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.activities.by-activityid.assignment",
    path: "/learning/instructor/courses/[courseId]/activities/[activityId]/assignment",
    title: "Learning · Instructor · Courses · courseId · Activities · activityId · Assignment",
    description: "App Router page at /learning/instructor/courses/[courseId]/activities/[activityId]/assignment",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/activities/[activityId]/assignment/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.activities.by-activityid.lab",
    path: "/learning/instructor/courses/[courseId]/activities/[activityId]/lab",
    title: "Learning · Instructor · Courses · courseId · Activities · activityId · Lab",
    description: "App Router page at /learning/instructor/courses/[courseId]/activities/[activityId]/lab",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/activities/[activityId]/lab/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.activities.by-activityid.project",
    path: "/learning/instructor/courses/[courseId]/activities/[activityId]/project",
    title: "Learning · Instructor · Courses · courseId · Activities · activityId · Project",
    description: "App Router page at /learning/instructor/courses/[courseId]/activities/[activityId]/project",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/activities/[activityId]/project/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.activities.by-activityid.questions",
    path: "/learning/instructor/courses/[courseId]/activities/[activityId]/questions",
    title: "Learning · Instructor · Courses · courseId · Activities · activityId · Questions",
    description: "App Router page at /learning/instructor/courses/[courseId]/activities/[activityId]/questions",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/activities/[activityId]/questions/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.assignments.by-submissionid",
    path: "/learning/instructor/courses/[courseId]/assignments/[submissionId]",
    title: "Learning · Instructor · Courses · courseId · Assignments · submissionId",
    description: "App Router page at /learning/instructor/courses/[courseId]/assignments/[submissionId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid.assignments",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/assignments/[submissionId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.assignments",
    path: "/learning/instructor/courses/[courseId]/assignments",
    title: "Learning · Instructor · Courses · courseId · Assignments",
    description: "App Router page at /learning/instructor/courses/[courseId]/assignments",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/assignments/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.calendar",
    path: "/learning/instructor/courses/[courseId]/calendar",
    title: "Learning · Instructor · Courses · courseId · Calendar",
    description: "App Router page at /learning/instructor/courses/[courseId]/calendar",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/calendar/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.completion",
    path: "/learning/instructor/courses/[courseId]/completion",
    title: "Learning · Instructor · Courses · courseId · Completion",
    description: "App Router page at /learning/instructor/courses/[courseId]/completion",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/completion/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.learners.by-learneruserid",
    path: "/learning/instructor/courses/[courseId]/learners/[learnerUserId]",
    title: "Learning · Instructor · Courses · courseId · Learners · learnerUserId",
    description: "App Router page at /learning/instructor/courses/[courseId]/learners/[learnerUserId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid.learners",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/learners/[learnerUserId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.learners",
    path: "/learning/instructor/courses/[courseId]/learners",
    title: "Learning · Instructor · Courses · courseId · Learners",
    description: "App Router page at /learning/instructor/courses/[courseId]/learners",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/learners/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.lessons.by-lessonid",
    path: "/learning/instructor/courses/[courseId]/lessons/[lessonId]",
    title: "Learning · Instructor · Courses · courseId · Lessons · lessonId",
    description: "App Router page at /learning/instructor/courses/[courseId]/lessons/[lessonId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/lessons/[lessonId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.live.by-sessionid",
    path: "/learning/instructor/courses/[courseId]/live/[sessionId]",
    title: "Learning · Instructor · Courses · courseId · Live · sessionId",
    description: "App Router page at /learning/instructor/courses/[courseId]/live/[sessionId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid.live",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/live/[sessionId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.live",
    path: "/learning/instructor/courses/[courseId]/live",
    title: "Learning · Instructor · Courses · courseId · Live",
    description: "App Router page at /learning/instructor/courses/[courseId]/live",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/live/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.manual-review.by-attemptid",
    path: "/learning/instructor/courses/[courseId]/manual-review/[attemptId]",
    title: "Learning · Instructor · Courses · courseId · Manual Review · attemptId",
    description: "App Router page at /learning/instructor/courses/[courseId]/manual-review/[attemptId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid.manual-review",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/manual-review/[attemptId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.manual-review",
    path: "/learning/instructor/courses/[courseId]/manual-review",
    title: "Learning · Instructor · Courses · courseId · Manual Review",
    description: "App Router page at /learning/instructor/courses/[courseId]/manual-review",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/manual-review/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.overview",
    path: "/learning/instructor/courses/[courseId]/overview",
    title: "Learning · Instructor · Courses · courseId · Overview",
    description: "App Router page at /learning/instructor/courses/[courseId]/overview",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/overview/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid",
    path: "/learning/instructor/courses/[courseId]",
    title: "Learning · Instructor · Courses · courseId",
    description: "App Router page at /learning/instructor/courses/[courseId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.projects.by-submissionid",
    path: "/learning/instructor/courses/[courseId]/projects/[submissionId]",
    title: "Learning · Instructor · Courses · courseId · Projects · submissionId",
    description: "App Router page at /learning/instructor/courses/[courseId]/projects/[submissionId]",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid.projects",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/projects/[submissionId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.projects",
    path: "/learning/instructor/courses/[courseId]/projects",
    title: "Learning · Instructor · Courses · courseId · Projects",
    description: "App Router page at /learning/instructor/courses/[courseId]/projects",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/projects/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.courses.by-courseid.resources",
    path: "/learning/instructor/courses/[courseId]/resources",
    title: "Learning · Instructor · Courses · courseId · Resources",
    description: "App Router page at /learning/instructor/courses/[courseId]/resources",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor.courses.by-courseid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/courses/[courseId]/resources/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor",
    path: "/learning/instructor",
    title: "Learning · Instructor",
    description: "App Router page at /learning/instructor",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.programs.by-programid.courses.new",
    path: "/learning/instructor/programs/[programId]/courses/new",
    title: "Learning · Instructor · Programs · programId · Courses · New",
    description: "App Router page at /learning/instructor/programs/[programId]/courses/new",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/programs/[programId]/courses/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.review",
    path: "/learning/instructor/review",
    title: "Learning · Instructor · Review",
    description: "App Router page at /learning/instructor/review",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "learning.instructor",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/review/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.spaces.by-spaceid.programs.new",
    path: "/learning/instructor/spaces/[spaceId]/programs/new",
    title: "Learning · Instructor · Spaces · spaceId · Programs · New",
    description: "App Router page at /learning/instructor/spaces/[spaceId]/programs/new",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.instructor",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/spaces/[spaceId]/programs/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.instructor.spaces.new",
    path: "/learning/instructor/spaces/new",
    title: "Learning · Instructor · Spaces · New",
    description: "App Router page at /learning/instructor/spaces/new",
    domain: "learning",
    section: "instructor",
    audience: "instructor",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "learning.instructor",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/instructor/spaces/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.lessons.by-lessonid.ai-tutor",
    path: "/learning/lessons/[lessonId]/ai-tutor",
    title: "Learning · Lessons · lessonId · Ai Tutor",
    description: "App Router page at /learning/lessons/[lessonId]/ai-tutor",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning.lessons.by-lessonid",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/lessons/[lessonId]/ai-tutor/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.lessons.by-lessonid",
    path: "/learning/lessons/[lessonId]",
    title: "Learning · Lessons · lessonId",
    description: "App Router page at /learning/lessons/[lessonId]",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/lessons/[lessonId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning",
    path: "/learning",
    title: "Learning",
    description: "App Router page at /learning",
    domain: "learning",
    section: "hub",
    audience: "public",
    access: "public",
    navigationVisibility: "primary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "learning.transcript",
    path: "/learning/transcript",
    title: "Learning · Transcript",
    description: "App Router page at /learning/transcript",
    domain: "learning",
    section: "learner",
    audience: "learner",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "learning",
    legacy: false,
    deprecated: false,
    sourceFile: "app/learning/transcript/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "live.by-roomid",
    path: "/live/[roomId]",
    title: "Live · roomId",
    description: "App Router page at /live/[roomId]",
    domain: "content",
    section: "live",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "live",
    legacy: false,
    deprecated: false,
    sourceFile: "app/live/[roomId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "live.media-lab",
    path: "/live/media-lab",
    title: "Live · Media Lab",
    description: "App Router page at /live/media-lab",
    domain: "content",
    section: "live",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "live",
    legacy: true,
    deprecated: false,
    sourceFile: "app/live/media-lab/page.tsx",
    status: "legacy",
    orphan: false,
  },
  {
    id: "live",
    path: "/live",
    title: "Live",
    description: "App Router page at /live",
    domain: "content",
    section: "live",
    audience: "public",
    access: "public",
    navigationVisibility: "primary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/live/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "login",
    path: "/login",
    title: "Login",
    description: "App Router page at /login",
    domain: "identity",
    section: "auth",
    audience: "public",
    access: "public",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/login/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "messages",
    path: "/messages",
    title: "Messages",
    description: "App Router page at /messages",
    domain: "platform",
    section: "messages",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "primary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/messages/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "notifications",
    path: "/notifications",
    title: "Notifications",
    description: "App Router page at /notifications",
    domain: "platform",
    section: "notifications",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/notifications/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "platform.home",
    path: "/",
    title: "Home",
    description: "App Router page at /",
    domain: "platform",
    section: "home",
    audience: "public",
    access: "public",
    navigationVisibility: "primary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: null,
    legacy: false,
    deprecated: false,
    sourceFile: "app/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "post-journey",
    path: "/post-journey",
    title: "Post Journey",
    description: "App Router page at /post-journey",
    domain: "content",
    section: "journey",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: true,
    deprecated: false,
    sourceFile: "app/post-journey/page.tsx",
    status: "legacy",
    orphan: false,
  },
  {
    id: "privacy",
    path: "/privacy",
    title: "Privacy",
    description: "App Router page at /privacy",
    domain: "platform",
    section: "legal",
    audience: "public",
    access: "public",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/privacy/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "profile.by-username",
    path: "/profile/[username]",
    title: "Profile · username",
    description: "App Router page at /profile/[username]",
    domain: "profile",
    section: "public-profile",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "profile",
    legacy: false,
    deprecated: false,
    sourceFile: "app/profile/[username]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "profile",
    path: "/profile",
    title: "Profile",
    description: "App Router page at /profile",
    domain: "profile",
    section: "self",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/profile/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "register",
    path: "/register",
    title: "Register",
    description: "App Router page at /register",
    domain: "identity",
    section: "auth",
    audience: "public",
    access: "public",
    navigationVisibility: "hidden",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: true,
    deprecated: true,
    sourceFile: "app/register/page.tsx",
    status: "deprecated",
    orphan: true,
  },
  {
    id: "rewards",
    path: "/rewards",
    title: "Rewards",
    description: "App Router page at /rewards",
    domain: "platform",
    section: "rewards",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/rewards/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "saved",
    path: "/saved",
    title: "Saved",
    description: "App Router page at /saved",
    domain: "content",
    section: "saved",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/saved/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "search",
    path: "/search",
    title: "Search",
    description: "App Router page at /search",
    domain: "platform",
    section: "search",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/search/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.apply",
    path: "/seller/apply",
    title: "Seller · Apply",
    description: "App Router page at /seller/apply",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/apply/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller",
    path: "/seller",
    title: "Seller",
    description: "App Router page at /seller",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.products.by-productid",
    path: "/seller/products/[productId]",
    title: "Seller · Products · productId",
    description: "App Router page at /seller/products/[productId]",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "seller.products",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/products/[productId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.products.new",
    path: "/seller/products/new",
    title: "Seller · Products · New",
    description: "App Router page at /seller/products/new",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.products",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/products/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.products",
    path: "/seller/products",
    title: "Seller · Products",
    description: "App Router page at /seller/products",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/products/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.setup",
    path: "/seller/setup",
    title: "Seller · Setup",
    description: "App Router page at /seller/setup",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/setup/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.analytics",
    path: "/seller/store/analytics",
    title: "Seller · Store · Analytics",
    description: "App Router page at /seller/store/analytics",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/analytics/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.inventory",
    path: "/seller/store/inventory",
    title: "Seller · Store · Inventory",
    description: "App Router page at /seller/store/inventory",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/inventory/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.marketplace.by-productid",
    path: "/seller/store/marketplace/[productId]",
    title: "Seller · Store · Marketplace · productId",
    description: "App Router page at /seller/store/marketplace/[productId]",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "seller.store.marketplace",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/marketplace/[productId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.marketplace",
    path: "/seller/store/marketplace",
    title: "Seller · Store · Marketplace",
    description: "App Router page at /seller/store/marketplace",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/marketplace/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.orders.by-orderid",
    path: "/seller/store/orders/[orderId]",
    title: "Seller · Store · Orders · orderId",
    description: "App Router page at /seller/store/orders/[orderId]",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "seller.store.orders",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/orders/[orderId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.orders",
    path: "/seller/store/orders",
    title: "Seller · Store · Orders",
    description: "App Router page at /seller/store/orders",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/orders/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store",
    path: "/seller/store",
    title: "Seller · Store",
    description: "App Router page at /seller/store",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.products.by-productid.edit",
    path: "/seller/store/products/[productId]/edit",
    title: "Seller · Store · Products · productId · Edit",
    description: "App Router page at /seller/store/products/[productId]/edit",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "seller.store.products",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/products/[productId]/edit/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.products.new",
    path: "/seller/store/products/new",
    title: "Seller · Store · Products · New",
    description: "App Router page at /seller/store/products/new",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store.products",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/products/new/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.products",
    path: "/seller/store/products",
    title: "Seller · Store · Products",
    description: "App Router page at /seller/store/products",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/products/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.promotions",
    path: "/seller/store/promotions",
    title: "Seller · Store · Promotions",
    description: "App Router page at /seller/store/promotions",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/promotions/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "seller.store.shipping",
    path: "/seller/store/shipping",
    title: "Seller · Store · Shipping",
    description: "App Router page at /seller/store/shipping",
    domain: "commerce",
    section: "seller",
    audience: "seller",
    access: "role_gated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "seller.store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/seller/store/shipping/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "settings",
    path: "/settings",
    title: "Settings",
    description: "App Router page at /settings",
    domain: "settings",
    section: "account",
    audience: "member",
    access: "authenticated",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/settings/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "signup",
    path: "/signup",
    title: "Signup",
    description: "App Router page at /signup",
    domain: "identity",
    section: "auth",
    audience: "public",
    access: "public",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/signup/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.by-storeslug",
    path: "/store/[storeSlug]",
    title: "Store · storeSlug",
    description: "App Router page at /store/[storeSlug]",
    domain: "commerce",
    section: "storefront",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/[storeSlug]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.by-storeslug.product.by-productslug",
    path: "/store/[storeSlug]/product/[productSlug]",
    title: "Store · storeSlug · Product · productSlug",
    description: "App Router page at /store/[storeSlug]/product/[productSlug]",
    domain: "commerce",
    section: "storefront",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "store.by-storeslug",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/[storeSlug]/product/[productSlug]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.cart",
    path: "/store/cart",
    title: "Store · Cart",
    description: "App Router page at /store/cart",
    domain: "commerce",
    section: "buyer",
    audience: "buyer",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/cart/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.checkout",
    path: "/store/checkout",
    title: "Store · Checkout",
    description: "App Router page at /store/checkout",
    domain: "commerce",
    section: "buyer",
    audience: "buyer",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/checkout/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.orders.by-orderid",
    path: "/store/orders/[orderId]",
    title: "Store · Orders · orderId",
    description: "App Router page at /store/orders/[orderId]",
    domain: "commerce",
    section: "buyer",
    audience: "buyer",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: true,
    parentId: "store.orders",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/orders/[orderId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.orders",
    path: "/store/orders",
    title: "Store · Orders",
    description: "App Router page at /store/orders",
    domain: "commerce",
    section: "buyer",
    audience: "buyer",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/orders/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store",
    path: "/store",
    title: "Store",
    description: "App Router page at /store",
    domain: "commerce",
    section: "storefront",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.products.by-productid",
    path: "/store/products/[productId]",
    title: "Store · Products · productId",
    description: "App Router page at /store/products/[productId]",
    domain: "commerce",
    section: "storefront",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/products/[productId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.search",
    path: "/store/search",
    title: "Store · Search",
    description: "App Router page at /store/search",
    domain: "commerce",
    section: "storefront",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/search/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.shops.by-shopid",
    path: "/store/shops/[shopId]",
    title: "Store · Shops · shopId",
    description: "App Router page at /store/shops/[shopId]",
    domain: "commerce",
    section: "storefront",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/shops/[shopId]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "store.wishlist",
    path: "/store/wishlist",
    title: "Store · Wishlist",
    description: "App Router page at /store/wishlist",
    domain: "commerce",
    section: "buyer",
    audience: "buyer",
    access: "authenticated",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: true,
    dynamic: false,
    parentId: "store",
    legacy: false,
    deprecated: false,
    sourceFile: "app/store/wishlist/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "terms",
    path: "/terms",
    title: "Terms",
    description: "App Router page at /terms",
    domain: "platform",
    section: "legal",
    audience: "public",
    access: "public",
    navigationVisibility: "utility",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/terms/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "watch",
    path: "/watch",
    title: "Watch",
    description: "App Router page at /watch",
    domain: "content",
    section: "watch",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/watch/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "welcome",
    path: "/welcome",
    title: "Welcome",
    description: "App Router page at /welcome",
    domain: "platform",
    section: "welcome",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/welcome/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "world.city.by-cityslug",
    path: "/world/city/[citySlug]",
    title: "World · City · citySlug",
    description: "App Router page at /world/city/[citySlug]",
    domain: "platform",
    section: "world",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "world",
    legacy: false,
    deprecated: false,
    sourceFile: "app/world/city/[citySlug]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "world",
    path: "/world",
    title: "World",
    description: "App Router page at /world",
    domain: "platform",
    section: "world",
    audience: "public",
    access: "public",
    navigationVisibility: "primary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "platform.home",
    legacy: false,
    deprecated: false,
    sourceFile: "app/world/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "world.place.by-placeslug",
    path: "/world/place/[placeSlug]",
    title: "World · Place · placeSlug",
    description: "App Router page at /world/place/[placeSlug]",
    domain: "platform",
    section: "world",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: true,
    parentId: "world",
    legacy: false,
    deprecated: false,
    sourceFile: "app/world/place/[placeSlug]/page.tsx",
    status: "active",
    orphan: false,
  },
  {
    id: "world.search",
    path: "/world/search",
    title: "World · Search",
    description: "App Router page at /world/search",
    domain: "platform",
    section: "world",
    audience: "public",
    access: "public",
    navigationVisibility: "secondary",
    adminOnly: false,
    authenticated: false,
    dynamic: false,
    parentId: "world",
    legacy: false,
    deprecated: false,
    sourceFile: "app/world/search/page.tsx",
    status: "active",
    orphan: false,
  },
] as const;

export const PAGE_OVERLAP_NOTES: readonly PageOverlapNote[] = [
  { paths: ["/signup","/register"] as const, note: "Duplicate auth entry — register is legacy alias of signup" },
  { paths: ["/","/discover"] as const, note: "Discover is forever Home alias" },
  { paths: ["/seller/products","/seller/store/products"] as const, note: "Seller product surfaces overlap (legacy seller/products vs store products)" },
  { paths: ["/city/[citySlug]","/world/city/[citySlug]"] as const, note: "City prototype vs World city canonical" },
  { paths: ["/store/products/[productId]","/store/[storeSlug]/product/[productSlug]"] as const, note: "Id-based PDP vs slug PDP" },
  { paths: ["/store/shops/[shopId]","/store/[storeSlug]"] as const, note: "Id-based shop vs slug storefront" },
] as const;

export const PAGE_REGISTRY_VERSION = "UMTUBA_UNIFIED_PAGE_REGISTRY_V1" as const;
