-- UMTUBA local-only bootstrap precursor for public.posts
--
-- WHY THIS FILE EXISTS
--   20260712_auth_profiles_posts_rls.sql ALTERs public.posts (adds user_id + RLS)
--   but never CREATEs it. P0 supabase/README.md (commit 523117c7) says that
--   migration creates "posts.user_id column" after pasting into the hosted
--   SQL Editor — the table was created in the dashboard, not in git.
--
--   Exhaustive search (this worktree, sibling Desktop/umtuba web checkouts,
--   named SHAs d354fd2 / 866749ed / 09155b15 / 455fdca8, git log -S/-G for
--   CREATE TABLE posts, schema/dump/baseline artifacts) found NO CREATE TABLE
--   public.posts and NO production schema dump. Do not apply this to production
--   (the hosted table already exists).
--
-- COLUMN EVIDENCE (pre-20260712 shape only — later migrations ADD the rest)
--   id              bigint identity PK
--                   20260713_social_interactions_v1.sql:
--                   post_id bigint not null references public.posts (id)
--                   P0 DatabasePost.id: number; P0 createPost omits id
--                   identity: dashboard-created table + insert-without-id
--   content         text not null default ''
--                   P0 DatabasePost.content: string; P0 allows empty when image
--   post_type       text not null
--                   P0 insert + DatabasePost; 20260713_video_posts_v1 indexes it
--   author_name / author_username / author_avatar  text not null
--                   P0 posts.ts insert + DatabasePost
--   image_url / video_url  text nullable
--                   P0 DatabasePost string | null; P0 insert sends null video_url
--   likes / comments / shares  integer not null default 0
--                   P0 insert sends 0; DatabasePost number;
--                   20260713_social adds CHECK >= 0 without adding NOT NULL
--   created_at      timestamptz not null default now()
--                   P0 select/order; 20260712 indexes created_at desc;
--                   insert omits it; timestamptz matches later post_* tables
--
-- NOT included (added by later committed migrations, do not invent here):
--   user_id (20260712), video_path/mime/byte_size (20260713_video),
--   saves/views (20260713_social), media pipeline columns (20260730),
--   article_id (20260865).
--
-- LOCAL BOOTSTRAP ONLY. Safe to re-run. Does not rewrite 20260712+.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  content text not null default '',
  post_type text not null,
  author_name text not null,
  author_username text not null,
  author_avatar text not null,
  image_url text,
  video_url text,
  likes integer not null default 0,
  comments integer not null default 0,
  shares integer not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.posts is
  'Local bootstrap precursor. Reconstructs the dashboard-era posts table that 20260712 assumed. Not a production dump.';
