-- SUPERSEDED by supabase/migrations/20260929_world_platform_curated_places_v1.sql
-- TASK: CENTRAL_WORLD_CURATED_PLACES_V1
-- The V2 proposal is now the applied ownership model:
-- nullable owner_user_id, curated_by owner|platform, required provenance for
-- platform rows, GUC/service_role ingest, no fake auth.users.
-- Apply the migration file via supabase db query --linked --file (not db push).
